### ISSUE TITLE
Nerf taser

### ISSUE THREAD

**Issue by teeworlds-fan** [fokkonaut/F-DDrace#16]
Add a cooldown for taser or something, bcs i was killed too many times by taser spammers, its unfair.
+ Anyone can use aimbot, so its super op.

**Comment by ChillerDragon** [comment]
Even max taser level freezes you less than 3 seconds so you can not keep a tee frozen with one taser. So to block all it needs is one tactical shot that lets the enemy fall into freeze fast enough. And that would still be possible with a longer delay.

I feel like a delay could influence the core gameplay feeling and long time laser players might get confused with their muzzle memory.

But to be fair I feel your point. And back then when I first implemented the taser in ddnet++ I planned to add a fail rate. So there could be a chance that the taser shot "fails". It still fires but it kinda looks like a lightning and does not hit where you aim.

![taser_fail](https://user-images.githubusercontent.com/20344300/91535806-058d8580-e914-11ea-96a7-923fa357c26a.png)

But this is also kinda weird so I am not too sure if something should be changed. Since taser is not too hard to combat or obtain its still balanced enough in my opinion.

**Comment by fokkonaut** [comment]
Max taser freezes you still for < 1 second.

**Comment by o-be-one** [comment]
Could be really fun to have chances to fail taser shots :D ! Like instead you have a tear emote if it fails ^^.
