### ISSUE TITLE
As a player, i would like to know if owned plots are available to trade

### ISSUE THREAD

**Issue by o-be-one** [fokkonaut/F-DDrace#21]
Hello,

could be nice if there is kind of an auction for plots. Actually players can sell their plots, but if you don't see the chat, or are away when they sell it, you miss the information and they may miss a sale too.

What could be nice and probably not that hard to add: in real estate shop as a line in plots informations giving the price of owned plots that are to sell.

I think the regular price of plots should stay even if the plot is to sell, it's an information to considere when a plot is to sell and also it allows new players in plots to know the value if they would like to wait for plot expiration.

Thanks.

**Comment by ChillerDragon** [comment]
A ``/plot sales`` list would be nice indeed. Im not sure what a nice solution is to trades with offline players. Because currently the in game name is used to get the account name which would not be possible when the seller is offline. A bit ugly but functional would be a new command like ``/plot buy_id <plot id>`` and then the output of plot sales includes plot ids and in game names of the seller.
