### ISSUE TITLE
XP and/or money for arresting gangsters

### ISSUE THREAD

**Issue by frutijitsu** [fokkonaut/F-DDrace#75]

**Comment by ChillerDragon** [comment]
Money is planned xp is not too avoid farming with friends.

**Comment by fokkonaut** [comment]
I was about to implement this but my first thought was "Ah, that can be abused." I think this will not happen, a player drops his wallet that should be enough, I guess.

**Comment by swarfey** [comment]
A small reward like 1000 money + 250 xp would make no sense to abuse tho, especially since the touch-spawn-kill bug got fixxed and it would be more profitable to race 10x and get the money-xp-bomb every 5 min, instead of waiting 10 min for the tee to get out of jail
Also, which police officer works for free? x)

**Comment by fokkonaut** [comment]
closed by #80
