### ISSUE TITLE
Safezones

### ISSUE THREAD

**Issue by Emilcha** [fokkonaut/F-DDrace#91]
Make solo or no hook no hit zone in weird places where u could just go take a pee without having the fear of getting killed.

**Comment by ChillerDragon** [comment]
Join spectators to avoid getting killed. It would desirable if at no point in time a tee is untouchable. Sadly that is broken already.

**Comment by BulgarianTee** [comment]
Joining spectators would get you killed 100% of the time, meaning if you are mid race and want to rest, you can't just join spectators and be safe since you die and being safe doesn't matter. But still, I think safe points are something you need to make yourself, since the server is a type of gamemode where afk-ing is quite common, that means that the ways of being safe during afk-ing should be more creative than just some safezone that will be abused. Making your own defense using your weapons and hookable blocks etc. is what you should do when you want to go afk, in my opinion it should stay like that to avoid abuse and all the bugs and stuff that will happen if safezones were to be added.
