### ISSUE TITLE
Taser rework

### ISSUE THREAD

**Issue by SoulyVEVO** [fokkonaut/F-DDrace#94]
![taser](https://user-images.githubusercontent.com/61762251/110604425-5d8d2a80-8188-11eb-9593-3335fb1e840a.png)

In my opinion the whole idea of limited taser ammo was pretty bad and it didnt quite fix the problem.
The problem was people constantly spamming taser which was overpowered on its own and even more broken when combined with multi jumps.

My idea to fix this is to remove battery ammo and instead give taser a "freeze strength delay"
On each 0.3s one bullet will be added to your ammo hud, each bullet acts as 0.10s of freeze time.
Total number of those bullets depends on your taser upgrade level *(would be 7 bullets with max upgrade)*
Each shot resets bullets back to 0.
Bullets can load even when taser is not currently in hand.
![iliketurtles](https://user-images.githubusercontent.com/61762251/110616129-80254080-8194-11eb-8ff1-8cf8c989f17d.gif)
This forces people to use taser as a secondary weapon rather than the main weapon to fight with.
Just holding the fire key will leave you with a faster fire rate but really low amount of freeze time.

I would also propose to:
- add more taser upgrade levels up to 10 *(would give a total of 1s freeze time)*
- remove police level requirement to use taser *(would let people use it without having police rank)*

**Comment by ChillerDragon** [comment]
I like it. If it gets weaker with every shot we can set the fire delay back to the vanilla laser that would be nice.

Imo taser amo is a fun collectable, but you are right it does not solve the issue. Since portal users have ammo on their respawn route they are always full. I would keep the ammo but change it to be more of a thing to collect and share than something that impacts actual pvp. Like increase max ammo by a lot. So the average racer never runs out of ammo if not spamming it 24/7.

Not sure about higher freeze times tho. I think the current one is a pretty sweet spot but im ready to be convinced otherwise.

Removing it from police would make police even more useless. What is your motivation for it? The reason the taser was introduced is to stop spawnblockers or other types of gangsters. Since the police can only jail frozen players there had to be a way for police to freeze gangster anywhere in the map and send them to jail. I know it probably has never been used like that. I assume you want taser to be more wide spread for non tryhard farmers and remove the requirement of getting level 30. Even tho I was aiming to avoid unbeatable imbalances the server is still aiming to be farm2win or at least getting and advantage.

tl;r
Really enjoy the refilling idea. Not sure about the other things.

**Comment by SoulyVEVO** [comment]
> Removing it from police would make police even more useless. What is your motivation for it?
@ChillerDragon i just saw that many people were confused by it and they didnt knew that they need highier police level to use it

**Comment by fokkonaut** [comment]
Fixed by https://github.com/fokkonaut/F-DDrace/commit/1fc87147358d47d5a646a908bf1d1d9d84dde37f
